
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author josec
 */
public class Nuevainterfaz extends javax.swing.JFrame {

    private boolean activarMouseMove = false;

    /**
     * Creates new form Nuevainterfaz
     */
    public Nuevainterfaz() {

        // Inicializar componentes
        initComponents();

        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        //  Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/Logo.png")).getImage());

        // MouseMove
        jButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelMouseMove.setForeground(Color.GREEN);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMouseMove.setForeground(Color.RED);
            }
        });

        // MouseDown
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMouseDown.setForeground(Color.GREEN);
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMouseDown.setForeground(Color.RED);
            }
        });

        // Change
        jTextField.addCaretListener(new javax.swing.event.CaretListener() {
            @Override
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jLabelChange.setForeground(Color.GREEN);
            }
        });

        // Click
        jButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelClick.setForeground(Color.GREEN);
            }
        });

        // GetFocus
        jTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabelGetFocus.setForeground(Color.GREEN);
                jLabelLostFocus.setForeground(Color.RED);
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabelLostFocus.setForeground(Color.GREEN);
                jLabelGetFocus.setForeground(Color.RED);
                
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLostFocus = new javax.swing.JLabel();
        jLabelMouseMove = new javax.swing.JLabel();
        jLabelMouseDown = new javax.swing.JLabel();
        jLabelChange = new javax.swing.JLabel();
        jLabelClick = new javax.swing.JLabel();
        jLabelGetFocus = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        jTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Interfaz Eventos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, 80));

        jPanel2.setBackground(new java.awt.Color(28, 28, 28));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLostFocus.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelLostFocus.setForeground(new java.awt.Color(255, 51, 51));
        jLabelLostFocus.setText("LostFocus Activo");
        jPanel2.add(jLabelLostFocus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabelMouseMove.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelMouseMove.setForeground(new java.awt.Color(255, 51, 51));
        jLabelMouseMove.setText("MouseMove Activo");
        jPanel2.add(jLabelMouseMove, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabelMouseDown.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelMouseDown.setForeground(new java.awt.Color(255, 51, 51));
        jLabelMouseDown.setText("MouseDown Activo");
        jPanel2.add(jLabelMouseDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabelChange.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelChange.setForeground(new java.awt.Color(255, 51, 51));
        jLabelChange.setText("Change Activo");
        jPanel2.add(jLabelChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabelClick.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelClick.setForeground(new java.awt.Color(255, 51, 51));
        jLabelClick.setText("Click Activo");
        jPanel2.add(jLabelClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabelGetFocus.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelGetFocus.setForeground(new java.awt.Color(255, 51, 51));
        jLabelGetFocus.setText("GetFocus Activo");
        jPanel2.add(jLabelGetFocus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 240, 320));

        jButton.setBackground(new java.awt.Color(28, 28, 28));
        jButton.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton.setText("Botón");
        jButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton.setFocusPainted(false);
        jButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonMouseMoved(evt);
            }
        });
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMouseExited(evt);
            }
        });
        jPanel1.add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 450, 120));

        jTextField.setBackground(new java.awt.Color(28, 28, 28));
        jTextField.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jTextField.setForeground(new java.awt.Color(255, 255, 255));
        jTextField.setText("Hola");
        jPanel1.add(jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 450, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseMoved
    }//GEN-LAST:event_jButtonMouseMoved

    private void jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseExited
        jLabelMouseMove.setForeground(Color.RED);
    }//GEN-LAST:event_jButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevainterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevainterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevainterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevainterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevainterfaz().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JLabel jLabelClick;
    private javax.swing.JLabel jLabelGetFocus;
    private javax.swing.JLabel jLabelLostFocus;
    private javax.swing.JLabel jLabelMouseDown;
    private javax.swing.JLabel jLabelMouseMove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
