package clasesMapeadas;
// Generated 10 dic 2024, 11:13:39 by Hibernate Tools 5.4.33.Final

/**
 * Lleva generated by hbm2java
 */
public class Lleva implements java.io.Serializable {

	private LlevaId id;
	private Camisetas camisetas;
	private Etapas etapas;
	private Ciclistas ciclistas;

	public Lleva() {
	}

	public Lleva(LlevaId id, Camisetas camisetas, Etapas etapas, Ciclistas ciclistas) {
		this.id = id;
		this.camisetas = camisetas;
		this.etapas = etapas;
		this.ciclistas = ciclistas;
	}

	public LlevaId getId() {
		return this.id;
	}

	public void setId(LlevaId id) {
		this.id = id;
	}

	public Camisetas getCamisetas() {
		return this.camisetas;
	}

	public void setCamisetas(Camisetas camisetas) {
		this.camisetas = camisetas;
	}

	public Etapas getEtapas() {
		return this.etapas;
	}

	public void setEtapas(Etapas etapas) {
		this.etapas = etapas;
	}

	public Ciclistas getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Ciclistas ciclistas) {
		this.ciclistas = ciclistas;
	}

}
