
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josec
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    // Inicializar atributos de la clase
    ArrayList arrayVowels = new ArrayList();
    ArrayList arrayConsonants = new ArrayList();
    DefaultListModel modelo1 = new DefaultListModel();
    DefaultListModel modelo2 = new DefaultListModel();
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        // Asignar el modelo a nuestras JLists
        jListVowels.setModel(modelo1); 
        jListConsonants.setModel(modelo2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jLabelEnterWord = new javax.swing.JLabel();
        jTextFieldWord = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jLabelVowels = new javax.swing.JLabel();
        jLabelConsonants = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListVowels = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListConsonants = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBackground.setBackground(new java.awt.Color(27, 40, 56));

        jLabelEnterWord.setBackground(new java.awt.Color(27, 40, 56));
        jLabelEnterWord.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        jLabelEnterWord.setForeground(new java.awt.Color(199, 213, 224));
        jLabelEnterWord.setText("Ingrese una palabra:");

        jTextFieldWord.setBackground(new java.awt.Color(27, 40, 56));
        jTextFieldWord.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        jTextFieldWord.setForeground(new java.awt.Color(199, 213, 224));
        jTextFieldWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWordActionPerformed(evt);
            }
        });

        jButtonEnter.setBackground(new java.awt.Color(27, 40, 56));
        jButtonEnter.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(199, 213, 224));
        jButtonEnter.setText("Ingresar");
        jButtonEnter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 213, 224), 3, true));
        jButtonEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jLabelVowels.setBackground(new java.awt.Color(27, 40, 56));
        jLabelVowels.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        jLabelVowels.setForeground(new java.awt.Color(199, 213, 224));
        jLabelVowels.setText("Comienza por vocal");

        jLabelConsonants.setBackground(new java.awt.Color(27, 40, 56));
        jLabelConsonants.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        jLabelConsonants.setForeground(new java.awt.Color(199, 213, 224));
        jLabelConsonants.setText("Comienza por consonante");

        jScrollPane3.setBackground(new java.awt.Color(27, 40, 56));

        jListVowels.setBackground(new java.awt.Color(27, 40, 56));
        jListVowels.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224)));
        jListVowels.setForeground(new java.awt.Color(199, 213, 224));
        jScrollPane3.setViewportView(jListVowels);

        jScrollPane4.setBackground(new java.awt.Color(27, 40, 56));

        jListConsonants.setBackground(new java.awt.Color(27, 40, 56));
        jListConsonants.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224)));
        jListConsonants.setForeground(new java.awt.Color(199, 213, 224));
        jScrollPane4.setViewportView(jListConsonants);

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelEnterWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldWord))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelVowels)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConsonants))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnterWord)
                    .addComponent(jTextFieldWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVowels)
                    .addComponent(jLabelConsonants))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método para comprobar que sea una palabra y no un número
    private static boolean isWord(String input) {
        return input.matches("[a-zA-Z]+");
    }
    
    // Método para comprobar si la palabra empieza por vocal
    private static boolean startVowel(String word) {
    
        // Pasar la palabra a mayúsculas para realizar bien la comparación
        word = word.toUpperCase();
        
        // Coger el primer caracter de la palabra
        char firstChar = word.charAt(0);
        
        // Comprobar que sea vocal
        if (firstChar == 'A' || firstChar == 'E' || firstChar == 'I' || firstChar == 'O' || firstChar == 'U') {
            return true;
        } else {
            return false;
        }
       
    }
    
 
    private void jTextFieldWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWordActionPerformed
   
    }//GEN-LAST:event_jTextFieldWordActionPerformed
   
    
    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        
        // Establecer una variable con la palabra ingresada en el JTetxField
        String word = jTextFieldWord.getText();
        
        // Comprobar que sea una palabra
        if (isWord(word)) {
                        
            // Comprobar si empieza por vocal o no
            if (startVowel(word)) {
                
                // Añadimos la palabra al array correspondiente
                arrayVowels.add(word);
                
                // Mostrar los elementos del array
                modelo1.removeAllElements();
                for (int i = 0; i < arrayVowels.size(); i++) {
                    modelo1.addElement(arrayVowels.get(i));
                }
                
            } else {
                
                // Añadimos la palabra al array correspondiente
                arrayConsonants.add(word);
                
                // Mostrar los elementos del array
                modelo2.removeAllElements();
                for (int i = 0; i < arrayConsonants.size(); i++) {
                    modelo2.addElement(arrayConsonants.get(i));
                }
                
            }
            
        }
        
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabelConsonants;
    private javax.swing.JLabel jLabelEnterWord;
    private javax.swing.JLabel jLabelVowels;
    private javax.swing.JList<String> jListConsonants;
    private javax.swing.JList<String> jListVowels;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextFieldWord;
    // End of variables declaration//GEN-END:variables
}
