/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividadmusica;

import java.applet.Applet;
import java.applet.AudioClip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author josec
 */
public class audio extends javax.swing.JFrame {

    AudioClip audio;

    /**
     * Creates new form audio
     */
    public audio() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/actividadmusica/imgs/Logo.png")).getImage());
        audio = Applet.newAudioClip(getClass().getResource("/actividadmusica/audios/ladrido.wav"));
    }

    public void reproducirSonido() {
        audio.play();
    }

    public void detenerSonido() {
        audio.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelImagenn1 = new jpanelimagenn.JPanelImagenn();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonDog = new javax.swing.JRadioButton();
        jRadioButtonCat = new javax.swing.JRadioButton();
        jRadioButtonParrot = new javax.swing.JRadioButton();
        jRadioButtonWhale = new javax.swing.JRadioButton();
        jButtonStop = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jButtonEnviarRespuesta = new javax.swing.JButton();
        jLabelRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File("C:/Users/josec/Documents/NetBeansProjects/TEMA-3/ActividadMusica/src/actividadmusica/imgs/Selva.jpg"), 1.0f));

        jLabelTitle.setBackground(new java.awt.Color(75, 118, 76));
        jLabelTitle.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText(" ANIMAL SOUNDS EXAM ");
        jLabelTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(106, 65, 57), 5, true));
        jLabelTitle.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(106, 65, 57));
        jLabel1.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Listen the following sounds and inidcate what type of animal it is. ");
        jLabel1.setOpaque(true);

        buttonGroup1.add(jRadioButtonDog);
        jRadioButtonDog.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 30)); // NOI18N
        jRadioButtonDog.setForeground(new java.awt.Color(106, 65, 57));
        jRadioButtonDog.setText("Dog");

        buttonGroup1.add(jRadioButtonCat);
        jRadioButtonCat.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 30)); // NOI18N
        jRadioButtonCat.setForeground(new java.awt.Color(106, 65, 57));
        jRadioButtonCat.setText("Cat");

        buttonGroup1.add(jRadioButtonParrot);
        jRadioButtonParrot.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 30)); // NOI18N
        jRadioButtonParrot.setForeground(new java.awt.Color(106, 65, 57));
        jRadioButtonParrot.setText("Parrot");

        buttonGroup1.add(jRadioButtonWhale);
        jRadioButtonWhale.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 30)); // NOI18N
        jRadioButtonWhale.setForeground(new java.awt.Color(106, 65, 57));
        jRadioButtonWhale.setText("Whale");

        jButtonStop.setBackground(new java.awt.Color(75, 118, 76));
        jButtonStop.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 18)); // NOI18N
        jButtonStop.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStop.setText("Stop");
        jButtonStop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(106, 65, 57), 3, true));
        jButtonStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStop.setFocusPainted(false);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jButtonPlay.setBackground(new java.awt.Color(75, 118, 76));
        jButtonPlay.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 18)); // NOI18N
        jButtonPlay.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlay.setText("Play");
        jButtonPlay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(106, 65, 57), 3, true));
        jButtonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlay.setFocusPainted(false);
        jButtonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseClicked(evt);
            }
        });

        jButtonEnviarRespuesta.setBackground(new java.awt.Color(75, 118, 76));
        jButtonEnviarRespuesta.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 18)); // NOI18N
        jButtonEnviarRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviarRespuesta.setText("Enviar Respuesta");
        jButtonEnviarRespuesta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(106, 65, 57), 3, true));
        jButtonEnviarRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEnviarRespuesta.setFocusPainted(false);
        jButtonEnviarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarRespuestaActionPerformed(evt);
            }
        });

        jLabelRespuesta.setBackground(new java.awt.Color(75, 118, 76));
        jLabelRespuesta.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 1, 36)); // NOI18N
        jLabelRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRespuesta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(106, 65, 57), 5, true));
        jLabelRespuesta.setOpaque(true);

        javax.swing.GroupLayout jPanelImagenn1Layout = new javax.swing.GroupLayout(jPanelImagenn1);
        jPanelImagenn1.setLayout(jPanelImagenn1Layout);
        jPanelImagenn1Layout.setHorizontalGroup(
            jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                        .addGroup(jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDog)
                            .addComponent(jRadioButtonParrot)
                            .addComponent(jRadioButtonCat)
                            .addComponent(jRadioButtonWhale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEnviarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonPlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                        .addGap(301, 301, 301))))
            .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRespuesta)
                .addGap(99, 99, 99))
        );
        jPanelImagenn1Layout.setVerticalGroup(
            jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelRespuesta))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonParrot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonWhale))
                    .addComponent(jButtonEnviarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayMouseClicked
        reproducirSonido();
    }//GEN-LAST:event_jButtonPlayMouseClicked

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        detenerSonido();
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonEnviarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarRespuestaActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Está seguro de sus respuestas?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {

            if (jRadioButtonDog.isSelected()) {
                jLabelRespuesta.setText(" TRUE ");
            } else {
                jLabelRespuesta.setText(" FALSE ");
            }

        }


    }//GEN-LAST:event_jButtonEnviarRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new audio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonEnviarRespuesta;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRespuesta;
    private javax.swing.JLabel jLabelTitle;
    private jpanelimagenn.JPanelImagenn jPanelImagenn1;
    private javax.swing.JRadioButton jRadioButtonCat;
    private javax.swing.JRadioButton jRadioButtonDog;
    private javax.swing.JRadioButton jRadioButtonParrot;
    private javax.swing.JRadioButton jRadioButtonWhale;
    // End of variables declaration//GEN-END:variables
}
