
import java.awt.Color;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josec
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    // Atributos de la clase
    JLabel[] labelsRespuestas;
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1A = new javax.swing.JRadioButton();
        jRadioButton1B = new javax.swing.JRadioButton();
        jRadioButton1D = new javax.swing.JRadioButton();
        jRadioButton1C = new javax.swing.JRadioButton();
        jLabelRespuesta1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2A = new javax.swing.JRadioButton();
        jRadioButton2B = new javax.swing.JRadioButton();
        jRadioButton2D = new javax.swing.JRadioButton();
        jRadioButton2C = new javax.swing.JRadioButton();
        jLabelRespuesta2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton3A = new javax.swing.JRadioButton();
        jRadioButton3B = new javax.swing.JRadioButton();
        jRadioButton3D = new javax.swing.JRadioButton();
        jRadioButton3C = new javax.swing.JRadioButton();
        jLabelRespuesta3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelRespuesta4 = new javax.swing.JLabel();
        jCheckBox4A = new javax.swing.JCheckBox();
        jCheckBox4B = new javax.swing.JCheckBox();
        jCheckBox4C = new javax.swing.JCheckBox();
        jCheckBox4D = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 40, 56));
        jPanel1.setForeground(new java.awt.Color(199, 213, 224));

        jLabel1.setBackground(new java.awt.Color(27, 40, 56));
        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 192, 244));
        jLabel1.setText("Ingrese la respuesta correcta");

        jPanel2.setBackground(new java.awt.Color(27, 40, 56));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Cúal es el resultado de 4*6+3+2*2?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(199, 213, 224))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(199, 213, 224));

        jRadioButton1A.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup1.add(jRadioButton1A);
        jRadioButton1A.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton1A.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton1A.setText("58");

        jRadioButton1B.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup1.add(jRadioButton1B);
        jRadioButton1B.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton1B.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton1B.setText("31");

        jRadioButton1D.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup1.add(jRadioButton1D);
        jRadioButton1D.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton1D.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton1D.setText("40");

        jRadioButton1C.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup1.add(jRadioButton1C);
        jRadioButton1C.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton1C.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton1C.setText("34");

        jLabelRespuesta1.setBackground(new java.awt.Color(27, 40, 56));
        jLabelRespuesta1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabelRespuesta1.setForeground(new java.awt.Color(199, 213, 224));
        jLabelRespuesta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRespuesta1.setText("RESPUESTA");
        jLabelRespuesta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1D)
                    .addComponent(jRadioButton1A)
                    .addComponent(jRadioButton1C)
                    .addComponent(jRadioButton1B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButton1A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1D)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(27, 40, 56));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Cúal es el nombre del quinto planeta?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(199, 213, 224))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(199, 213, 224));

        jRadioButton2A.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup2.add(jRadioButton2A);
        jRadioButton2A.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton2A.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton2A.setText("Marte");

        jRadioButton2B.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup2.add(jRadioButton2B);
        jRadioButton2B.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton2B.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton2B.setText("Júpiter");

        jRadioButton2D.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup2.add(jRadioButton2D);
        jRadioButton2D.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton2D.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton2D.setText("Saturno");

        jRadioButton2C.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup2.add(jRadioButton2C);
        jRadioButton2C.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton2C.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton2C.setText("Tierra");

        jLabelRespuesta2.setBackground(new java.awt.Color(27, 40, 56));
        jLabelRespuesta2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabelRespuesta2.setForeground(new java.awt.Color(199, 213, 224));
        jLabelRespuesta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRespuesta2.setText("RESPUESTA");
        jLabelRespuesta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2D)
                    .addComponent(jRadioButton2A)
                    .addComponent(jRadioButton2C)
                    .addComponent(jRadioButton2B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButton2A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2D)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(27, 40, 56));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Cúal es la palabra con error ortográfico?", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(199, 213, 224))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(199, 213, 224));

        jRadioButton3A.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup3.add(jRadioButton3A);
        jRadioButton3A.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton3A.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton3A.setText("Ola");

        jRadioButton3B.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup3.add(jRadioButton3B);
        jRadioButton3B.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton3B.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton3B.setText("Desición");

        jRadioButton3D.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup3.add(jRadioButton3D);
        jRadioButton3D.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton3D.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton3D.setText("Ahí");

        jRadioButton3C.setBackground(new java.awt.Color(27, 40, 56));
        buttonGroup3.add(jRadioButton3C);
        jRadioButton3C.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jRadioButton3C.setForeground(new java.awt.Color(199, 213, 224));
        jRadioButton3C.setText("Hay");

        jLabelRespuesta3.setBackground(new java.awt.Color(27, 40, 56));
        jLabelRespuesta3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabelRespuesta3.setForeground(new java.awt.Color(199, 213, 224));
        jLabelRespuesta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRespuesta3.setText("RESPUESTA");
        jLabelRespuesta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3D)
                    .addComponent(jRadioButton3A)
                    .addComponent(jRadioButton3C)
                    .addComponent(jRadioButton3B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabelRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jRadioButton3A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3D)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(27, 40, 56));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marca los sinónimos de inteligente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(199, 213, 224))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(199, 213, 224));

        jLabelRespuesta4.setBackground(new java.awt.Color(27, 40, 56));
        jLabelRespuesta4.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabelRespuesta4.setForeground(new java.awt.Color(199, 213, 224));
        jLabelRespuesta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRespuesta4.setText("RESPUESTA");
        jLabelRespuesta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224)));

        jCheckBox4A.setBackground(new java.awt.Color(27, 40, 56));
        jCheckBox4A.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jCheckBox4A.setForeground(new java.awt.Color(199, 213, 224));
        jCheckBox4A.setText("Sagaz");

        jCheckBox4B.setBackground(new java.awt.Color(27, 40, 56));
        jCheckBox4B.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jCheckBox4B.setForeground(new java.awt.Color(199, 213, 224));
        jCheckBox4B.setText("Listo");

        jCheckBox4C.setBackground(new java.awt.Color(27, 40, 56));
        jCheckBox4C.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jCheckBox4C.setForeground(new java.awt.Color(199, 213, 224));
        jCheckBox4C.setText("Lerdo");

        jCheckBox4D.setBackground(new java.awt.Color(27, 40, 56));
        jCheckBox4D.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jCheckBox4D.setForeground(new java.awt.Color(199, 213, 224));
        jCheckBox4D.setText("Astuto");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBox4D)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4A)
                            .addComponent(jCheckBox4B)
                            .addComponent(jCheckBox4C))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jCheckBox4A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4C)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4D)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(27, 40, 56));
        jButton1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(199, 213, 224));
        jButton1.setText("Mostrar Respuestas");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224), 3));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Método para comprobar que la respuesta sea correcta
    private boolean correctAnswer (int questionNumber) {
        
        // Comprobar que pregunta hay que verificar
        switch (questionNumber) { 
            case 0:  
                return jRadioButton1B.isSelected();
            case 1:
                return jRadioButton2B.isSelected();
            case 2:
                return jRadioButton3B.isSelected();
            case 3:
                return jCheckBox4A.isSelected() && jCheckBox4B.isSelected() && jCheckBox4D.isSelected() && !jCheckBox4C.isSelected();
        }
        
        // Devuelve false si no es ninguna de las preguntas
        return false;
        
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        // Inicializar el array de Labels
        JLabel[] labelsRespuestas = { jLabelRespuesta1, jLabelRespuesta2, jLabelRespuesta3, jLabelRespuesta4 };
        
        for (int i = 0; i <= 3; i++) {
        
            if (correctAnswer(i)) {
                labelsRespuestas[i].setText("BIEN");
                labelsRespuestas[i].setForeground(Color.decode("#cef89c"));
            } else {
                labelsRespuestas[i].setText("MAL");
                labelsRespuestas[i].setForeground(Color.decode("#ff3333"));
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox4A;
    private javax.swing.JCheckBox jCheckBox4B;
    private javax.swing.JCheckBox jCheckBox4C;
    private javax.swing.JCheckBox jCheckBox4D;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRespuesta1;
    private javax.swing.JLabel jLabelRespuesta2;
    private javax.swing.JLabel jLabelRespuesta3;
    private javax.swing.JLabel jLabelRespuesta4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1A;
    private javax.swing.JRadioButton jRadioButton1B;
    private javax.swing.JRadioButton jRadioButton1C;
    private javax.swing.JRadioButton jRadioButton1D;
    private javax.swing.JRadioButton jRadioButton2A;
    private javax.swing.JRadioButton jRadioButton2B;
    private javax.swing.JRadioButton jRadioButton2C;
    private javax.swing.JRadioButton jRadioButton2D;
    private javax.swing.JRadioButton jRadioButton3A;
    private javax.swing.JRadioButton jRadioButton3B;
    private javax.swing.JRadioButton jRadioButton3C;
    private javax.swing.JRadioButton jRadioButton3D;
    // End of variables declaration//GEN-END:variables
}
