/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio.gui;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author josec
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    // Establecer el ArrayList como atributo de la clase
    private ArrayList<String> words;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        words = new ArrayList<>(); // Inicializar el ArrayList
        inicializarTabla(); // Inicializar la tabla
    }

    // Método para inicializar la table
    private void inicializarTabla() {

        // Inicializar el modelo de la tabla
        DefaultTableModel dtm = new DefaultTableModel();

        // Añadir un título a la columna de la tabla
        dtm.setColumnIdentifiers(new String[]{"Palabras"});

        // Establecer el modelo de la tabla
        jTableWords.setModel(dtm);

        // Obtener el encabezado de la tabla
        JTableHeader tableHeader = jTableWords.getTableHeader();

        // Cambiar la fuente del encabezado y el color
        tableHeader.setFont(new Font("Lucida Sans Typewriter", Font.BOLD, 14));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldWord = new javax.swing.JTextField();
        jButtonShow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableWords = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 40, 56));

        jLabel1.setBackground(new java.awt.Color(27, 40, 56));
        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(199, 213, 224));
        jLabel1.setText("Ingrese la Palabra: ");

        jTextFieldWord.setBackground(new java.awt.Color(27, 40, 56));
        jTextFieldWord.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jTextFieldWord.setForeground(new java.awt.Color(199, 213, 224));

        jButtonShow.setBackground(new java.awt.Color(27, 40, 56));
        jButtonShow.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jButtonShow.setForeground(new java.awt.Color(199, 213, 224));
        jButtonShow.setText("Mostrar");
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(27, 40, 56));
        jScrollPane1.setForeground(new java.awt.Color(199, 213, 224));

        jTableWords.setBackground(new java.awt.Color(42, 71, 94));
        jTableWords.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 213, 224)));
        jTableWords.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jTableWords.setForeground(new java.awt.Color(199, 213, 224));
        jTableWords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTableWords.setGridColor(new java.awt.Color(27, 40, 56));
        jTableWords.setName(""); // NOI18N
        jTableWords.setSelectionForeground(new java.awt.Color(27, 40, 56));
        jScrollPane1.setViewportView(jTableWords);
        jTableWords.getAccessibleContext().setAccessibleName("");

        jButtonAdd.setBackground(new java.awt.Color(27, 40, 56));
        jButtonAdd.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(199, 213, 224));
        jButtonAdd.setText("Ingresar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldWord))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método para comprobar que sea una palabra
    public boolean isWord(String word) {
        return word.matches("[a-zA-Z]+");
    }

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        // Asignar a una variable la palabra que intriduzca el usuario
        String word = jTextFieldWord.getText();

        // Comprobar la longitud
        if (word.length() < 10) {

            // Comprobar que no esté vacío o sea número
            if (word.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No has introducido ningun valor", "Error", JOptionPane.ERROR_MESSAGE);
            } else if(!isWord(word)) {
                JOptionPane.showMessageDialog(null, "Valor intriducido incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // Añadir la palabra al ArrayList
                words.add(word);
            }
        }

        // Limpiar el campo de texto después de escribir la palabra
        jTextFieldWord.setText("");

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed

        if (words.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay palabras ingresadas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            
            DefaultTableModel dtm = (DefaultTableModel) jTableWords.getModel();

            // Limpiar la tabla antes de añadir las palabras
            dtm.setRowCount(0);

            // Recorrer el ArrayList e ir añadiendo las palabras
            for (String word : words) {
                dtm.addRow(new Object[]{word});
            }
        }


    }//GEN-LAST:event_jButtonShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableWords;
    private javax.swing.JTextField jTextFieldWord;
    // End of variables declaration//GEN-END:variables
}
