/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author josec
 */
public class Acceso extends javax.swing.JFrame {

    /**
     * Creates new form Acceso
     */
    public Acceso() {

        // Inicializar los componentes
        initComponents();

        // Establecer un tamaño determinado a la interfaz
        setSize(997, 376);

        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        // Establecer imagen fondo
        String relativePath = "src/imgs/fondoAcceso.jpg";
        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File(relativePath), 1.0f));
        
        //  Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/logoTeamRocket.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagenn1 = new jpanelimagenn.JPanelImagenn();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonOjo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImagenn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCESO");
        jPanelImagenn1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 997, 56));

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        jPanelImagenn1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");
        jPanelImagenn1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jTextFieldUsuario.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanelImagenn1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 114, 280, 30));

        jPasswordFieldContraseña.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jPasswordFieldContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPanelImagenn1.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 172, 220, 30));

        jButtonEntrar.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconoEntrar.png"))); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanelImagenn1.add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 242, 140, 50));

        jButtonOjo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ojoBlanco.png"))); // NOI18N
        jButtonOjo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOjo.setFocusPainted(false);
        jButtonOjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOjoActionPerformed(evt);
            }
        });
        jPanelImagenn1.add(jButtonOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOjoActionPerformed

        // Comprobar si el carácter de eco es el predeterminado (es decir, la contraseña está oculta)
        if (jPasswordFieldContraseña.getEchoChar() == (char) 0) {

            // Si el campo está visible, lo ocultamos
            jPasswordFieldContraseña.setEchoChar('*');

        } else {

            // Si el campo está oculto, lo mostramos
            jPasswordFieldContraseña.setEchoChar((char) 0);

        }
    }//GEN-LAST:event_jButtonOjoActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed

        if (camposVacios()) {

            // Mostrar mensaje de error
            JOptionPane.showMessageDialog(this,
                "Error: Los cmapos no pueden estar vacíos.",
                "Error de entrada",
                JOptionPane.ERROR_MESSAGE);

        } else {

            if (soloLetras(jTextFieldUsuario.getText().toString())) {

                // Cerrar ventana actual
                dispose();

                // Crear siguiente ventana
                Seleccion pantallaPrincipal = new Seleccion();

                // Hacer visible la siguiente pantalla
                pantallaPrincipal.setVisible(true);

            } else {

                // Mostrar mensaje de error
                JOptionPane.showMessageDialog(this,
                    "Error: No se pueden introducir letras en el campo de usuario.",
                    "Error de entrada",
                    JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    public boolean soloLetras(String cadena) {
        return cadena.matches("^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ ]+$");
    }

    public boolean camposVacios() {
        return jTextFieldUsuario.getText().toString().isEmpty() || jPasswordFieldContraseña.getPassword().length == 0;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonOjo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private jpanelimagenn.JPanelImagenn jPanelImagenn1;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
