/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Proveedor;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

/**
 *
 * @author josec
 */
public class IngresoProveedores extends javax.swing.JFrame {

    private Tabla tabla;

    /**
     * Creates new form IngresoProveedores
     */
    public IngresoProveedores() {

        // Inicializar los componentes
        initComponents();

        // Establecer un tamaño determinado a la interfaz
        setSize(1069, 540);

        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        // Cargar comboBoxes
        cargarComboBoxConImagenes();

        //  Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/logoTeamRocket.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jComboBoxPaises = new javax.swing.JComboBox<>();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonNuevoProveedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DNI:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Empresa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("País:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-mail:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ingreso de Proveedores");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1070, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1070, 10));

        jTextFieldCorreo.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jPanel1.add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 370, 30));

        jTextFieldDNI.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jPanel1.add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 370, 30));

        jTextFieldEmpresa.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jPanel1.add(jTextFieldEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 370, 30));

        jTextFieldDireccion.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jPanel1.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 370, 30));

        jComboBoxPaises.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jComboBoxPaises.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxPaises, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 370, 40));

        jTextFieldTelefono.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jPanel1.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 370, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/enfermera.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, -1, -1));

        jButtonLimpiar.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/borrar.png"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 300, 50));

        jButtonNuevoProveedor.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButtonNuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconoGuardar.png"))); // NOI18N
        jButtonNuevoProveedor.setText("Añadir Proveedor");
        jButtonNuevoProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 300, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dni.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/empresa.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/direccion.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/telefono.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/paises.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/gmail.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        int resultado = JOptionPane.showConfirmDialog(this,
                "¿Seguro que quieres borrar los campos?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (resultado == JOptionPane.YES_NO_OPTION) {
            // Limpiar los datos
            jTextFieldDNI.setText("");
            jTextFieldCorreo.setText("");
            jTextFieldDireccion.setText("");
            jTextFieldEmpresa.setText("");
            jTextFieldTelefono.setText("");
        }


    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoProveedorActionPerformed

        // Comprobar que los campos no estén vacíos
        if (camposVacios()) {

            // Mostrar mensaje de error
            JOptionPane.showMessageDialog(this,
                    "Error: Los campos no pueden estar vacíos",
                    "Error de entrada",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            // Comprobar que la dirección de correo sea válida
            if (verificarDireccionCorreo(jTextFieldCorreo.getText().toString())) {

                // Comprobar que el DNI tiene la longitud adecuada
                if (jTextFieldDNI.getText().toString().length() == 9) {

                    // Comprobar que en el campo de la empresa solo se hayan introducido letras
                    if (soloLetras(jTextFieldEmpresa.getText().toString())) {

                        // Comrobar que en el campo del teléfono solo se hayan introducido números
                        if (soloNumeros(jTextFieldTelefono.getText().toString())) {

                            // Comprobar que en el campo del teléfono se haya introducido un teléfono válido
                            if (jTextFieldTelefono.getText().toString().length() == 9) {

                                // Asignar los valores introducidos por el usuario a variables
                                String dni = jTextFieldDNI.getText().toString();
                                String empresa = jTextFieldEmpresa.getText().toString();
                                String direccion = jTextFieldDireccion.getText().toString();
                                int telefono = Integer.parseInt(jTextFieldTelefono.getText().toString());
                                String pais = jComboBoxPaises.getSelectedItem().toString();
                                String correo = jTextFieldCorreo.getText().toString();

                                // Crear objeto de tipo Proveedor
                                Proveedor p = new Proveedor(dni, empresa, direccion, telefono, pais, correo);

                                // Cerrar ventana actual    
                                dispose();

                                // Crear la nueva tabla
                                tabla = new Tabla();

                                // Pasarle la pelicula a la tabla
                                tabla.añadirProveedor(p);

                                // Actualizra la tabla con el proveedor
                                tabla.actualizarTabla();

                                // Hacer visible la ventana con la tabla
                                tabla.setVisible(true);

                                // Cerrar ventana actual
                                dispose();

                            } else {

                                // Mostrar mensaje de error
                                JOptionPane.showMessageDialog(this,
                                        "Error: El teléfono debe se der de 9 dígitos.",
                                        "Error de entrada",
                                        JOptionPane.ERROR_MESSAGE);

                            }

                        } else {

                            // Mostrar mensaje de error
                            JOptionPane.showMessageDialog(this,
                                    "Error: No se pueden introducir letras en el campo del teléfono.",
                                    "Error de entrada",
                                    JOptionPane.ERROR_MESSAGE);

                        }

                    } else {

                        // Mostrar mensaje de error
                        JOptionPane.showMessageDialog(this,
                                "Error: No se pueden introducir números en el campo de la empresa.",
                                "Error de entrada",
                                JOptionPane.ERROR_MESSAGE);

                    }

                } else {

                    // Mostrar mensaje de error
                    JOptionPane.showMessageDialog(this,
                            "Error: El DNI debe de contener 9 caracteres.",
                            "Error de entrada",
                            JOptionPane.ERROR_MESSAGE);

                }

            } else {

                // Mostrar mensaje de error
                JOptionPane.showMessageDialog(this,
                        "Error: Dirección de correo no válida.",
                        "Error de entrada",
                        JOptionPane.ERROR_MESSAGE);

            }

        }


    }//GEN-LAST:event_jButtonNuevoProveedorActionPerformed

    public boolean soloLetras(String cadena) {
        return cadena.matches("^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ ]+$");
    }

    public boolean soloNumeros(String cadena) {
        return cadena.matches("^[0-9]+$");
    }

    private void cargarComboBoxConImagenes() {

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("España");
        model.addElement("Bélgica");
        model.addElement("Brasil");
        model.addElement("USA");
        jComboBoxPaises.setModel(model);
        jComboBoxPaises.setRenderer(new ListCellRenderer<String>() {

            @Override
            public Component getListCellRendererComponent(JList<? extends String> list, String value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel label = new JLabel();
                switch (value) {

                    case "España":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/espana.png")));
                        label.setText("España");
                        break;

                    case "Bélgica":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/belgica.png")));
                        label.setText("Bélgica");
                        break;

                    case "Brasil":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/brasil.png")));
                        label.setText("Brasil");
                        break;

                    case "USA":
                        label.setIcon(new ImageIcon(getClass().getResource("/imgs/estados-unidos.png")));
                        label.setText("USA");
                        break;

                }

                if (isSelected) {
                    label.setBackground(list.getSelectionBackground());
                    label.setOpaque(true);
                }

                return label;

            }

        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonNuevoProveedor;
    private javax.swing.JComboBox<String> jComboBoxPaises;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    private boolean camposVacios() {
        return jTextFieldCorreo.getText().toString().isEmpty()
                || jTextFieldDNI.getText().toString().isEmpty()
                || jTextFieldDireccion.getText().toString().isEmpty()
                || jTextFieldEmpresa.getText().toString().isEmpty()
                || jTextFieldTelefono.getText().toString().isEmpty();
    }

    // Método que verifica mediante una expresión regular si es una dirección de correo válida
    public boolean verificarDireccionCorreo(String direccionCorreo) {
        return direccionCorreo.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");
    }

}
