/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author josec
 */
public class Seleccion extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion
     */
    public Seleccion() {

        // Inicializar los componentes
        initComponents();

        // Establecer un tamaño determinado a la interfaz
        setSize(790, 448);

        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        // Establecer imagen fondo
        String relativePath = "src/imgs/fondoSeleccion.jpg";
        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File(relativePath), 1.0f));
        
        //  Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/logoTeamRocket.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagenn1 = new jpanelimagenn.JPanelImagenn();
        jLabelAltas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonProveedores = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File("C:/Program Files/NetBeans 8.2"), 0.5f));
        jPanelImagenn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAltas.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabelAltas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAltas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAltas.setText("ALTAS");
        jPanelImagenn1.add(jLabelAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 290, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 0, 25));

        jButtonProveedores.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButtonProveedores.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconoPlanta.png"))); // NOI18N
        jButtonProveedores.setText("Proveedores");
        jButtonProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProveedores);

        jButtonClientes.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconoFuego.png"))); // NOI18N
        jButtonClientes.setText("Clientes");
        jButtonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClientes);

        jButtonProductos.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButtonProductos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconoAgua.png"))); // NOI18N
        jButtonProductos.setText("Productos");
        jButtonProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonProductos);

        jPanelImagenn1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 320));
        jPanelImagenn1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagenn1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed

        // Llamar al método para avisar al usuario que el botón no está aún habilitado
        mostrarMensajeBotonDeshabilitado();

    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProveedoresActionPerformed

        // Cerrar ventana actual
        dispose();

        // Crear siguiente ventana
        IngresoProveedores ingresoProveedores = new IngresoProveedores();

        // Hacer visible la siguiente pantalla
        ingresoProveedores.setVisible(true);

    }//GEN-LAST:event_jButtonProveedoresActionPerformed

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed

        // Llamar al método para avisar al usuario que el botón no está aún habilitado
        mostrarMensajeBotonDeshabilitado();

    }//GEN-LAST:event_jButtonProductosActionPerformed

    public void mostrarMensajeBotonDeshabilitado() {

        // Mostrar mensaje de información
        JOptionPane.showMessageDialog(this,
                "No está habilitada esta opción",
                "Botón deshabilitado",
                JOptionPane.INFORMATION_MESSAGE);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAltas;
    private javax.swing.JPanel jPanel1;
    private jpanelimagenn.JPanelImagenn jPanelImagenn1;
    // End of variables declaration//GEN-END:variables
}
