/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.CentrarColumnas;
import clases.Proveedor;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author josec
 */
public class Tabla extends javax.swing.JFrame {

    private Proveedor proveedorAtributo = new Proveedor("", "", "", 0, "", "");

    /**
     * Creates new form Tabla
     */
    public Tabla() {

        // Inicializar los componentes
        initComponents();

        // Establecer un tamaño determinado a la interfaz
        setSize(980, 496);

        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        // Configurar el modelo de la tabla
        configurarModeloTabla();

        // Configurar Tabla
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        //  Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/logoTeamRocket.png")).getImage());

    }

    public void añadirProveedor(Proveedor p) {

        proveedorAtributo = p;

    }

    public void actualizarTabla() {

        // Comprobar que no sea nulo el proveedor
        if (proveedorAtributo != null) {

            // Asignar el modelo de la tabla
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            // Asignarle los valores a la tabla
            dtm.addRow(new Object[]{
                proveedorAtributo.getDni(),
                proveedorAtributo.getEmpresa(),
                proveedorAtributo.getDireccion(),
                proveedorAtributo.getTelefono(),
                proveedorAtributo.getPais(),
                proveedorAtributo.getCorreo()
            });
        }
    }

    private void configurarModeloTabla() {

        // Crear el modelo de la tabla
        DefaultTableModel dtm = new DefaultTableModel();

        // Cambiar el nombre de la cabecera
        dtm.setColumnIdentifiers(new String[]{"DNI", "Empresa", "Dirección", "Teléfono", "País", "Correo"});

        // Establecer el modelo a la tabla
        jTable1.setModel(dtm);

        // Aplicar el renderizador centrado a todas las columnas
        for (int i = 0; i < dtm.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(new CentrarColumnas());
        }

        // Centrar los encabezados de las columnas
        JTableHeader header = jTable1.getTableHeader();
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
