package clases;
// Generated 12 dic 2024, 17:44:35 by Hibernate Tools 5.4.33.Final

import java.math.BigInteger;

/**
 * Nuevosalumnos generated by hbm2java
 */
public class Nuevosalumnos implements java.io.Serializable {

	private BigInteger codalum;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String telef;

	public Nuevosalumnos() {
	}

	public Nuevosalumnos(BigInteger codalum) {
		this.codalum = codalum;
	}

	public Nuevosalumnos(BigInteger codalum, String nombre, String direccion, String poblacion, String telef) {
		this.codalum = codalum;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telef = telef;
	}

	public BigInteger getCodalum() {
		return this.codalum;
	}

	public void setCodalum(BigInteger codalum) {
		this.codalum = codalum;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTelef() {
		return this.telef;
	}

	public void setTelef(String telef) {
		this.telef = telef;
	}

}
