/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author josec
 */
public class Acceso extends javax.swing.JFrame {

    /**
     * Creates new form Acceso
     */
    public Acceso() {
        
        // Inicializar los componentes
        initComponents();
        
        // Establecer un tamaño determinado a la interfaz
        setSize(1000, 575);
        
        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        //  Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/Logo.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagenn1 = new jpanelimagenn.JPanelImagenn();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNick = new javax.swing.JTextField();
        jButtonAcceder = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File("C:/Users/josec/Documents/NetBeansProjects/TEMA-4/ActividadResumenTema4/src/imgs/FondoPokemon.jpg"), 1.0f));
        jPanelImagenn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/IniciarSesion.png"))); // NOI18N
        jPanelImagenn1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 34, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Nick.png"))); // NOI18N
        jPanelImagenn1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Password.png"))); // NOI18N
        jPanelImagenn1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jTextFieldNick.setBackground(new java.awt.Color(59, 111, 184));
        jTextFieldNick.setFont(new java.awt.Font("Showcard Gothic", 0, 28)); // NOI18N
        jTextFieldNick.setForeground(new java.awt.Color(251, 203, 4));
        jPanelImagenn1.add(jTextFieldNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 430, 50));

        jButtonAcceder.setBackground(new java.awt.Color(59, 111, 184));
        jButtonAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Acceder.png"))); // NOI18N
        jButtonAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });
        jPanelImagenn1.add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        jPasswordFieldPassword.setBackground(new java.awt.Color(59, 111, 184));
        jPasswordFieldPassword.setFont(new java.awt.Font("Showcard Gothic", 0, 28)); // NOI18N
        jPasswordFieldPassword.setForeground(new java.awt.Color(251, 203, 4));
        jPanelImagenn1.add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 282, 430, 50));

        getContentPane().add(jPanelImagenn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed
        
        if (camposVacios()) {
            JOptionPane.showMessageDialog(this, "Error. Los campos no pueden estar vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            
            // Cerrar la ventana actual
            dispose();
            
            // Crear la nueva ventana de seleccion de personajes
            SeleccionPersonajes seleccionPersonajes = new SeleccionPersonajes();
            
            // Establecer el nick en la otra pantalla
            seleccionPersonajes.establecerNick(jTextFieldNick.getText());
            
            // Abrir la nueva ventana
            seleccionPersonajes.setVisible(true);
            
        }
               
    }//GEN-LAST:event_jButtonAccederActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private jpanelimagenn.JPanelImagenn jPanelImagenn1;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldNick;
    // End of variables declaration//GEN-END:variables

    private boolean camposVacios() {
        
        // Inicializar variable
        boolean estanVacios = false;
        
        // Comprobar que estén vacíos
        if (jTextFieldNick.getText().isEmpty() || jPasswordFieldPassword.getPassword().length == 0) {
            estanVacios = true;
        }
        
        // Devolver el valor booleano
        return estanVacios;
        
    }
}
