/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movealine;

import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author josec
 */
public class MoveLine extends javax.swing.JFrame {

    /**
     * Creates new form MoveLine
     */
    public MoveLine() {

        // Inicializar los componentes
        initComponents();

        // Establecer un tamaño determinado a la interfaz
        setSize(663, 510);

        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        // Establecer imagen fondo
        String relativePath = "src/imgs/fondoEspacio.jpg";
        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File(relativePath), 1.0f));
        
        // Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/iconoNave.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLeft = new javax.swing.JButton();
        jButtonRight = new javax.swing.JButton();
        jPanelImagenn1 = new jpanelimagenn.JPanelImagenn();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 19, 179));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLeft.setText("Left");
        jButtonLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 130, 50));

        jButtonRight.setText("Right");
        jButtonRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 120, 50));

        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File("C:/Users/josec/Documents/NetBeansProjects/TEMA-6/MoveALine/src/imgs/fondoEspacio.jpg"), 1.0f));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ovni.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagenn1Layout = new javax.swing.GroupLayout(jPanelImagenn1);
        jPanelImagenn1.setLayout(jPanelImagenn1Layout);
        jPanelImagenn1Layout.setHorizontalGroup(
            jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanelImagenn1Layout.setVerticalGroup(
            jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelImagenn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftActionPerformed

        // Obtener la posición actual del JLabel
        int x = jLabel1.getX();
        int y = jLabel1.getY();

        // Evitar que se salga del borde izquierdo
        if (x > 10) {

            // Mover hacia la izquierda disminuyendo la coordenada X
            jLabel1.setLocation(x - 10, y);

        }


    }//GEN-LAST:event_jButtonLeftActionPerformed

    private void jButtonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightActionPerformed

        // Obtener la posición actual del JLabel
        int x = jLabel1.getX();
        int y = jLabel1.getY();

        // Evitar que se salga del borde derecho
        if (x < 510) {

            // Mover hacia la derecha aumentando la coordenada X
            jLabel1.setLocation(x + 10, y);

        }

    }//GEN-LAST:event_jButtonRightActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLeft;
    private javax.swing.JButton jButtonRight;
    private javax.swing.JLabel jLabel1;
    private jpanelimagenn.JPanelImagenn jPanelImagenn1;
    // End of variables declaration//GEN-END:variables
}
