/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moveaball;

import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author josec
 */
public class MoveABall extends javax.swing.JFrame {

    /**
     * Creates new form MoveABall
     */
    public MoveABall() {

        // Inicializar los componentes
        initComponents();

        // Establecer un taaño a la interfaz
        setSize(682, 700);

        // Incapacitar al usuario para redimensionar el tamaño de la interfaz
        setResizable(false);

        // Centrar la interfaz en medio de la pantalla
        setLocationRelativeTo(null);

        // Establecer imagen fondo
        String relativePath = "src/imgs/fondoMar.jpg";
        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File(relativePath), 1.0f));

        // Establecer el icono de la interfaz
        this.setIconImage(new ImageIcon(getClass().getResource("/imgs/magikarp.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonUp = new javax.swing.JButton();
        jButtonLeft = new javax.swing.JButton();
        jButtonRight = new javax.swing.JButton();
        jButtonDown = new javax.swing.JButton();
        jPanelImagenn1 = new jpanelimagenn.JPanelImagenn();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/flechaArriba.png"))); // NOI18N
        jButtonUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 488, 70, 70));

        jButtonLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/flechaIzquierda.png"))); // NOI18N
        jButtonLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 80, 60));

        jButtonRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/flechaDerecha.png"))); // NOI18N
        jButtonRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 80, 60));

        jButtonDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/flechaAbajo.png"))); // NOI18N
        jButtonDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 70, 70));

        jPanelImagenn1.setImagenFondo(new jpanelimagenn.ImagenFondo(new java.io.File("C:/Users/josec/Documents/NetBeansProjects/TEMA-6/MoveABall/src/imgs/fondoMar.jpg"), 1.0f));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/magikarp.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagenn1Layout = new javax.swing.GroupLayout(jPanelImagenn1);
        jPanelImagenn1.setLayout(jPanelImagenn1Layout);
        jPanelImagenn1Layout.setHorizontalGroup(
            jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanelImagenn1Layout.setVerticalGroup(
            jPanelImagenn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenn1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelImagenn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 600, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed

        // Obtener la posición actual del JLabel
        int x = jLabel1.getX();
        int y = jLabel1.getY();

        // Evitar que se salga del borde superior
        if (y > 10) {

            // Mover hacia arriba disminuyendo la coordenada Y
            jLabel1.setLocation(x, y - 10);

        }

    }//GEN-LAST:event_jButtonUpActionPerformed

    private void jButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftActionPerformed

        // Obtener la posición actual del JLabel
        int x = jLabel1.getX();
        int y = jLabel1.getY();

        // Evitar que se salga del borde izquierdo
        if (x > 10) {

            // Mover hacia la izquierda disminuyendo la coordenada X
            jLabel1.setLocation(x - 10, y);

        }

    }//GEN-LAST:event_jButtonLeftActionPerformed

    private void jButtonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightActionPerformed

        // Obtener la posición actual del JLabel
        int x = jLabel1.getX();
        int y = jLabel1.getY();

        // Evitar que se salga del borde derecho
        if (x < 450) {

            // Mover hacia la derecha aumentando la coordenada X
            jLabel1.setLocation(x + 10, y);

        }


    }//GEN-LAST:event_jButtonRightActionPerformed

    private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed

        // Obtener la posición actual del JLabel
        int x = jLabel1.getX();
        int y = jLabel1.getY();

        // Evitar que se salga del borde superior
        if (y < 265) {

            // Mover hacia arriba disminuyendo la coordenada Y
            jLabel1.setLocation(x, y + 10);

        }

    }//GEN-LAST:event_jButtonDownActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonLeft;
    private javax.swing.JButton jButtonRight;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private jpanelimagenn.JPanelImagenn jPanelImagenn1;
    // End of variables declaration//GEN-END:variables
}
