/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testfigurasgeometricas.interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author josec
 */
public class Preguntas extends javax.swing.JDialog {

    private PantallaPrincipal pantallaPrincipal;

    /**
     * Creates new form Preguntas
     */
    public Preguntas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pantallaPrincipal = (PantallaPrincipal) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1A = new javax.swing.JRadioButton();
        jRadioButton1B = new javax.swing.JRadioButton();
        jRadioButton1C = new javax.swing.JRadioButton();
        jRadioButton1D = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2A = new javax.swing.JRadioButton();
        jRadioButton2B = new javax.swing.JRadioButton();
        jRadioButton2C = new javax.swing.JRadioButton();
        jRadioButton2D = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton3A = new javax.swing.JRadioButton();
        jRadioButton3B = new javax.swing.JRadioButton();
        jRadioButton3C = new javax.swing.JRadioButton();
        jRadioButton3D = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton4A = new javax.swing.JRadioButton();
        jRadioButton4B = new javax.swing.JRadioButton();
        jRadioButton4C = new javax.swing.JRadioButton();
        jRadioButton4D = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 28, 28));

        jPanel2.setBackground(new java.awt.Color(28, 28, 28));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1. ¿Cúal es la siguiente figura geométrica?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jRadioButton1A.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup1.add(jRadioButton1A);
        jRadioButton1A.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton1A.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1A.setText("Triángulo");

        jRadioButton1B.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup1.add(jRadioButton1B);
        jRadioButton1B.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton1B.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1B.setText("Cubo");

        jRadioButton1C.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup1.add(jRadioButton1C);
        jRadioButton1C.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton1C.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1C.setText("Círculo");

        jRadioButton1D.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup1.add(jRadioButton1D);
        jRadioButton1D.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton1D.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1D.setText("Pirámide");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testfigurasgeometricas/imgs/Cubo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1A)
                    .addComponent(jRadioButton1C)
                    .addComponent(jRadioButton1B)
                    .addComponent(jRadioButton1D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1B)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1C)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(127, 127, 127))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1D)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jPanel3.setBackground(new java.awt.Color(28, 28, 28));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2. ¿Cúal es la siguiente figura geométrica?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jRadioButton2A.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup2.add(jRadioButton2A);
        jRadioButton2A.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton2A.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2A.setText("Círculo");

        jRadioButton2B.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup2.add(jRadioButton2B);
        jRadioButton2B.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton2B.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2B.setText("Cubo");

        jRadioButton2C.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup2.add(jRadioButton2C);
        jRadioButton2C.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton2C.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2C.setText("Pirámide");

        jRadioButton2D.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup2.add(jRadioButton2D);
        jRadioButton2D.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton2D.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2D.setText("Octaedro");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testfigurasgeometricas/imgs/Piramide.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2A)
                    .addComponent(jRadioButton2C)
                    .addComponent(jRadioButton2B)
                    .addComponent(jRadioButton2D, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jRadioButton2A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2D)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(127, 127, 127))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(28, 28, 28));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "3. ¿Cúal es la siguiente figura geométrica?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jRadioButton3A.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup3.add(jRadioButton3A);
        jRadioButton3A.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton3A.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3A.setText("Cubo");

        jRadioButton3B.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup3.add(jRadioButton3B);
        jRadioButton3B.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton3B.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3B.setText("Triángulo");

        jRadioButton3C.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup3.add(jRadioButton3C);
        jRadioButton3C.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton3C.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3C.setText("Pentágono");

        jRadioButton3D.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup3.add(jRadioButton3D);
        jRadioButton3D.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton3D.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3D.setText("Octaedro");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testfigurasgeometricas/imgs/Octaedro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3A)
                    .addComponent(jRadioButton3C)
                    .addComponent(jRadioButton3B)
                    .addComponent(jRadioButton3D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jRadioButton3A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3C)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(127, 127, 127))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3D)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(28, 28, 28));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "4. ¿Cúal es la siguiente figura geométrica?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jRadioButton4A.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup4.add(jRadioButton4A);
        jRadioButton4A.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton4A.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4A.setText("Hexágono");

        jRadioButton4B.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup4.add(jRadioButton4B);
        jRadioButton4B.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton4B.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4B.setText("Cuadrado");

        jRadioButton4C.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup4.add(jRadioButton4C);
        jRadioButton4C.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton4C.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4C.setText("Círculo");

        jRadioButton4D.setBackground(new java.awt.Color(28, 28, 28));
        buttonGroup4.add(jRadioButton4D);
        jRadioButton4D.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jRadioButton4D.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4D.setText("Octaedro");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testfigurasgeometricas/imgs/Circulo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4A)
                    .addComponent(jRadioButton4C)
                    .addComponent(jRadioButton4B)
                    .addComponent(jRadioButton4D))
                .addGap(40, 40, 40)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jRadioButton4A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4B)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4C)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(127, 127, 127))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4D)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonEnviar.setBackground(new java.awt.Color(255, 102, 51));
        jButtonEnviar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setText("ENVIAR RESPUESTAS");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        
        float puntuacion = calcularPuntuacion();
        int aciertos = contarAciertos();
                
        pantallaPrincipal.establecerPuntuacion(puntuacion);
        pantallaPrincipal.establecerAciertos(aciertos);
        
        // Preguntar al usuario si está seguro de sus respuestas
        int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de sus respuestas?", 
            "Confirmar", 
            JOptionPane.YES_NO_OPTION);

        // Verificar la respuesta del usuario
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
            pantallaPrincipal.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Preguntas dialog = new Preguntas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1A;
    private javax.swing.JRadioButton jRadioButton1B;
    private javax.swing.JRadioButton jRadioButton1C;
    private javax.swing.JRadioButton jRadioButton1D;
    private javax.swing.JRadioButton jRadioButton2A;
    private javax.swing.JRadioButton jRadioButton2B;
    private javax.swing.JRadioButton jRadioButton2C;
    private javax.swing.JRadioButton jRadioButton2D;
    private javax.swing.JRadioButton jRadioButton3A;
    private javax.swing.JRadioButton jRadioButton3B;
    private javax.swing.JRadioButton jRadioButton3C;
    private javax.swing.JRadioButton jRadioButton3D;
    private javax.swing.JRadioButton jRadioButton4A;
    private javax.swing.JRadioButton jRadioButton4B;
    private javax.swing.JRadioButton jRadioButton4C;
    private javax.swing.JRadioButton jRadioButton4D;
    // End of variables declaration//GEN-END:variables

    private float calcularPuntuacion() {
        
        // Inicializar la variable
        float puntuacion = 0;

        // Comprobar la puntuación de la primera pregunta
        if (jRadioButton1B.isSelected()) {
            puntuacion += 2.5;
        }

        // Comprobar la puntuación de la segunda pregunta
        if (jRadioButton2C.isSelected()) {
            puntuacion += 2.5;
        }

        // Comprobar la puntuación de la tercera pregunta
        if (jRadioButton3D.isSelected()) {
            puntuacion += 2.5;
        }
        
        // Comprobar la puntuación de la cuarta pregunta
        if (jRadioButton4C.isSelected()) {
            puntuacion += 2.5;
        }
        
        // Devolver la puntuación que hay conseguido el usuario
        return puntuacion;
        
    }

    private int contarAciertos() {
        
        // Inicializar la variable
        int aciertos = 0;

        // Comprobar la puntuación de la primera pregunta
        if (jRadioButton1B.isSelected()) {
            aciertos++;
        }

        // Comprobar la puntuación de la segunda pregunta
        if (jRadioButton2C.isSelected()) {
            aciertos++;
        }

        // Comprobar la puntuación de la tercera pregunta
        if (jRadioButton3D.isSelected()) {
            aciertos++;
        }
        
        // Comprobar la puntuación de la cuarta pregunta
        if (jRadioButton4C.isSelected()) {
            aciertos++;
        }
        
        // Devolver la puntuación que hay conseguido el usuario
        return aciertos;
        
    }

}
